version: '3.5'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - ssl-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/client_certs:/etc/nginx/client_certs
    networks:
      - ssl-network
    depends_on:
      - app
networks:
  ssl-network:
    driver: bridge