version: '3.8'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./app:/etc/app
    ports:
      - "3000:3000"
    networks:
      - ssl-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
#    volumes:
#      - ./html:/var/www/html
#      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - ssl-network
    depends_on:
      - app
networks:
  ssl-network:
    driver: bridge