version: '3.5'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      -
    networks:
      - ssl-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - ssl-network
    depends_on:
      - app
networks:
  ssl-network:
    driver: bridge